version: '3.8'
  
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Finserv@2023
      POSTGRES_DB: dphone_customer
    ports:
      - "5433:5432"    
    networks:
      - backend

  app:
    image: customer-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dphone_customer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Finserv@2023
    networks:
      - backend      

    depends_on:
      - db

networks:
  backend:
    driver: bridge